import Button from './Button.vue';
import Navbar from './Navbar.vue';
import Popup from './Popup.vue';
import Pagination from './Pagination.vue';
import Video from './Video/Video.vue';
import Searchbar from './Searchbar/Searchbar.vue';
import Tooltip from './Tooltip.vue';
import Hoverbox from './Hoverbox.vue';
import Toggle from './Toggle.vue';
import Burger from './Burger.vue';

export const DKButton = Button;
export const DKNavbar = Navbar;
export const DKPopup = Popup;
export const DKPagination = Pagination;
export const DKVideo = Video;
export const DKSearchbar = Searchbar;
export const DKTooltip = Tooltip;
export const DKHoverbox = Hoverbox;
export const DKToggle = Toggle;
export const DKBurger = Burger;
